@startuml
(*) --> "计算拜访提醒边界"
if "提醒边界大于当前日期" then
--> [Yes] "Mute：将拜访提醒置为无效"
--> (*)
else
--> [No] "计算未拜访天数：\n<b>当前时间减去上次拜访时间</b>"
if "有该商家的提醒记录" then
--> [Yes] "更新提醒记录的上次拜访日期\n以及未拜访天数信息"
-> (*)
else
-> [No] "新增提醒记录"
Endif
--> (*)
@enduml