@startuml
(*) --> If "门店是否在私海" then
-> [是] If "\t门店纬度是否有上次拜访时间" then
--> [是] "比较当前时间和上次拜访时间"
--> If "是否需要提醒" then
--> [是] "新增或更新拜访记录"
else
--> [否] "将拜访记录置为无效"
--> (*)
Endif
else
--> [否] If "门店是否曾有负责BD" then
--> [是] "已存在门店，被分配或公海捡入"
--> "新增或更新拜访记录"
--> If "是否已存在拜访提醒记录" then
--> [是] "更新拜访提醒记录"
--> (*)
else
--> [否] "新增拜访提醒记录"
--> (*)
Endif
else
--> [否] "新录入门店，被分配或公海捡入"
--> "新增或更新拜访记录"
Endif
Endif
else
--> [否] (*)
Endif
@enduml