@startuml
(*)  --> "check input"
If "input is verbose" then
--> [Yes] "turn on verbosity" as tov
--> "run command"
else
--> "run command"
-down-> ===bar===
Endif
-->(*)

tov -down-> "use variable"
-down-> ===bar===
@enduml