@startuml
title 新增B端帐号（管理员）
(*)  --> if "user是否存在" then
--> [是] if "user是否有效（未删除）" then
--> [否] "错误：账户已被禁用"
-->(*)
else
--> [是] if "user_class是否存在" then
--> [是] if "\n\nuser_class是否有效" then
--> [是] "错误：已存在该角色"
-->(*)
else
--> [否] "错误：角色已被禁用"
-->(*)
endif
else
--> [否] if "是否存在C端user_class\n\n\n" then
--> [否] "新增user_class以及merchant"
-->(*)
else
--> [是] "1、发送短信给B端管理员\n2、使用C端密码\n3、新增user_class以及merchant"
-->(*)
endif
endif
endif
else
--> [否] "新增user，user_class以及merchant"
-->(*)
endif
@enduml